### PR TITLE
Add a WIP reimplementation of NBT tutorial as an example

### PR DESCRIPTION
**Pull request by ashwinvis**
This is an attempt to implement an existing tutorial to see if fathon can reproduce the same results. What I lack is the knowledge of how to make parameters match. Bugs may be present also. Could you take a look?

Static view: https://nbviewer.jupyter.org/github/ashwinvis/fathon/blob/nbt-tutorial/examples/nbt.ipynb

### CODE REVIEW

**Comment by ashwinvis** [comment]
Related to #4

**Comment by ashwinvis** [comment]
There is room for improvement, as I did not manage to match the result:

**Comment by stfbnc** [comment]
@ashwinvis Thank you for reimplementing the tutorial!
I tried it and it gives me a `H` different from yours and from that of the tutorial. Even though is not clear how to set the parameters from the tutorial, this behaviour is due to the choice of using a random signal to compute `H`. Since the signal is different in each analysis, a different `H` will also come out (even though not far from 0.5)

**Comment by ashwinvis** [comment]
Could you tell me what value of `H` you got? I seem to get H=0.48 everytime I re-run the notebook. I also do not understand why the X and Y axes are really different from the original tutorial. Do you have an explanation?

**Comment by stfbnc** [comment]
Running the notebook four times, I got 0.4759, 0.4805, 0.4919, 0.4827.

I've found the original code here https://github.com/germangh/NBT/blob/master/Biomarkers/nbt_DFA/nbt_doDFA.m. The scales are set on lines 100-103, and it is not a linear scale between 15 and 25, but a logarithmic scale, hence the different X and Y axes.
A logarithmic scale is an option still not available in fathon, but I'm planning to add it in the future.versions

**Pull request closed without merging**
